// SPDX-License-Identifier: GPL-2.0
/*
 * tcp_tracer.bpf.c — eBPF kernel-side program for TCP span tracing.
 *
 * This program attaches kprobes to the kernel functions tcp_sendmsg and
 * tcp_recvmsg to observe every TCP read and write that occurs on the system.
 * It also provides a generic uprobe section that the userspace loader can
 * attach to any user-space function to enrich the trace.
 *
 * Trace-ID generation and PID mapping
 * ------------------------------------
 * A BPF hash map (pid_trace_map) associates each observed PID with a
 * 64-bit trace_id.  When an inbound TCP read (tcp_recvmsg) is detected for
 * a PID, a fresh trace_id is generated and stored in the map — this marks
 * the start of a new request flow.  When the same PID later issues an
 * outbound TCP write (tcp_sendmsg), the existing trace_id is reused so that
 * the downstream send can be correlated with the original inbound request.
 *
 * Span logs
 * ---------
 * Every probe fires an event into the BPF perf-event array which the
 * userspace consumer reads and formats as a JSON span log.
 *
 * Build
 * -----
 *   See the top-level Makefile.  A vmlinux.h must be present in this
 *   directory before compilation (generated by `bpftool btf dump …`).
 */

#include "vmlinux.h"
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
#include <bpf/bpf_endian.h>
#include "tcp_tracer.h"

/* -------------------------------------------------------------------------
 * BPF maps
 * ---------------------------------------------------------------------- */

/*
 * pid_trace_map: maps a PID (u32) to its current trace_id (u64).
 *
 * Written when a new inbound request is detected (tcp_recvmsg), read (and
 * kept) when an outbound send is detected (tcp_sendmsg).
 */
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 10240);
    __type(key,   __u32);   /* pid       */
    __type(value, __u64);   /* trace_id  */
} pid_trace_map SEC(".maps");

/*
 * events: perf-event array through which span events are forwarded to the
 * userspace consumer.
 */
struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __uint(key_size,   sizeof(__u32));
    __uint(value_size, sizeof(__u32));
} events SEC(".maps");

/*
 * span_counter: per-CPU monotonic counter used to make span IDs unique.
 */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(max_entries, 1);
    __type(key,   __u32);
    __type(value, __u64);
} span_counter SEC(".maps");

/* -------------------------------------------------------------------------
 * Helper: trace-ID and span-ID generation
 * ---------------------------------------------------------------------- */

/*
 * generate_trace_id — produce a new trace identifier for the given PID.
 *
 * The ID is formed by XOR-combining the PID (shifted into the high 32 bits)
 * with the current kernel nanosecond timestamp so that repeated calls for
 * the same PID yield different values.
 */
static __always_inline __u64 generate_trace_id(__u32 pid)
{
    __u64 ts = bpf_ktime_get_ns();
    return ((__u64)pid << 32) ^ ts;
}

/*
 * get_or_create_trace_id — look up the trace_id for this PID; create one if
 * none exists yet.
 */
static __always_inline __u64 get_or_create_trace_id(__u32 pid)
{
    __u64 *val = bpf_map_lookup_elem(&pid_trace_map, &pid);
    if (val)
        return *val;

    __u64 new_id = generate_trace_id(pid);
    bpf_map_update_elem(&pid_trace_map, &pid, &new_id, BPF_ANY);
    return new_id;
}

/*
 * generate_span_id — produce a unique span identifier for this individual
 * event using a per-CPU counter XOR-combined with the current timestamp.
 */
static __always_inline __u64 generate_span_id(void)
{
    __u32 key = 0;
    __u64 ts  = bpf_ktime_get_ns();
    __u64 *counter = bpf_map_lookup_elem(&span_counter, &key);
    if (counter) {
        __u64 cnt = *counter + 1;
        *counter  = cnt;
        return ts ^ (cnt << 20);
    }
    return ts;
}

/* -------------------------------------------------------------------------
 * Helper: populate a tcp_event from the current execution context
 * ---------------------------------------------------------------------- */

/*
 * fill_event — fill all fields of *evt from the running task's context and
 * the given TCP socket, event type, and data length.
 *
 * Note: the trace_id field is set by get_or_create_trace_id() and
 * therefore reflects whatever trace_id was already stored in pid_trace_map
 * for this PID.  Callers that need to override it (e.g. tcp_recvmsg, which
 * generates a fresh id first) do so after calling fill_event().
 */
static __always_inline void fill_event(struct tcp_event *evt,
                                       struct sock *sk,
                                       __u32 event_type,
                                       __u32 data_len)
{
    __u64 pid_tgid    = bpf_get_current_pid_tgid();
    evt->pid          = (__u32)(pid_tgid >> 32);
    evt->tid          = (__u32)pid_tgid;
    evt->event_type   = event_type;
    evt->data_len     = data_len;
    evt->timestamp_ns = bpf_ktime_get_ns();
    bpf_get_current_comm(evt->comm, sizeof(evt->comm));

    evt->trace_id = get_or_create_trace_id(evt->pid);
    evt->span_id  = generate_span_id();

    /* Read addressing information from the kernel TCP socket. */
    BPF_CORE_READ_INTO(&evt->saddr, sk, __sk_common.skc_rcv_saddr);
    BPF_CORE_READ_INTO(&evt->daddr, sk, __sk_common.skc_daddr);
    evt->sport = BPF_CORE_READ(sk, __sk_common.skc_num);
    evt->dport = bpf_ntohs(BPF_CORE_READ(sk, __sk_common.skc_dport));
}

/* -------------------------------------------------------------------------
 * Kprobe: tcp_sendmsg — outgoing TCP data
 * ---------------------------------------------------------------------- */

/*
 * trace_tcp_sendmsg — fires whenever any process in the system calls the
 * kernel's tcp_sendmsg().
 *
 * The trace_id stored in pid_trace_map for the calling PID is reused so
 * that this outbound write can be correlated with the inbound request that
 * triggered it.  If no trace_id exists for this PID yet (e.g. the process
 * opened a connection without having received anything first), one is
 * created on demand.
 */
SEC("kprobe/tcp_sendmsg")
int BPF_KPROBE(trace_tcp_sendmsg, struct sock *sk, struct msghdr *msg,
               size_t size)
{
    struct tcp_event evt = {};
    fill_event(&evt, sk, EVENT_TCP_SEND, (__u32)size);
    bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU,
                          &evt, sizeof(evt));
    return 0;
}

/* -------------------------------------------------------------------------
 * Kprobe: tcp_recvmsg — incoming TCP data (new request boundary)
 * ---------------------------------------------------------------------- */

/*
 * trace_tcp_recvmsg — fires whenever any process in the system calls the
 * kernel's tcp_recvmsg().
 *
 * An inbound read marks the beginning of a new request flow.  A fresh
 * trace_id is generated and written into pid_trace_map, overwriting any
 * prior value for this PID.  This trace_id will then be reused by any
 * subsequent tcp_sendmsg() call from the same PID.
 */
SEC("kprobe/tcp_recvmsg")
int BPF_KPROBE(trace_tcp_recvmsg, struct sock *sk, struct msghdr *msg,
               size_t len, int flags, int *addr_len)
{
    __u64 pid_tgid = bpf_get_current_pid_tgid();
    __u32 pid      = (__u32)(pid_tgid >> 32);

    /* Generate and store a fresh trace_id for this new request.
     * fill_event() will look up this new value via get_or_create_trace_id(). */
    __u64 new_id = generate_trace_id(pid);
    bpf_map_update_elem(&pid_trace_map, &pid, &new_id, BPF_ANY);

    struct tcp_event evt = {};
    fill_event(&evt, sk, EVENT_TCP_RECV, (__u32)len);

    bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU,
                          &evt, sizeof(evt));
    return 0;
}

/* -------------------------------------------------------------------------
 * Uprobe: generic user-space function tracing
 * ---------------------------------------------------------------------- */

/*
 * trace_uprobe_entry — generic uprobe entry handler.
 *
 * The userspace loader (tcp_tracer.c) can attach this section to any
 * user-space function by specifying the target binary path and symbol (or
 * offset) via the --uprobe-binary / --uprobe-sym command-line flags.
 *
 * When the probe fires the current PID's trace_id (if any) is retrieved
 * from pid_trace_map and included in the emitted span event so that
 * user-space function calls can be correlated with the surrounding TCP
 * request flow.
 */
SEC("uprobe")
int BPF_KPROBE(trace_uprobe_entry)
{
    __u64 pid_tgid = bpf_get_current_pid_tgid();
    __u32 pid      = (__u32)(pid_tgid >> 32);

    struct tcp_event evt = {};
    evt.pid          = pid;
    evt.tid          = (__u32)pid_tgid;
    evt.event_type   = EVENT_UPROBE;
    evt.data_len     = 0;
    evt.timestamp_ns = bpf_ktime_get_ns();
    bpf_get_current_comm(evt.comm, sizeof(evt.comm));

    evt.trace_id = get_or_create_trace_id(pid);
    evt.span_id  = generate_span_id();

    bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU,
                          &evt, sizeof(evt));
    return 0;
}

char LICENSE[] SEC("license") = "GPL";
